var color = ["red","white","yellow","black","pink"];
document.write(color + "<br>");
// var a = prompt("Enter any color you want to add in the  beginning");
// color.unshift(a);
// document.write(color + "<br>");
// var b = prompt("Enter any color you want to add in the end");
// color.push(b);
// document.write(color + "<br>");
// var c = prompt("Enter any color you want to add in the  beginning");
// var d = prompt("Enter another color you want to add in the beginning");
// color.unshift(c,d);
// document.write(color + "<br>");
// color.shift();
// document.write(color + "<br>");
// color.pop();
// document.write(color + "<br>");
// var e = prompt("Enter color name you want to enter in array");
// var f = prompt("Enter index number at which you want to add the color");
// color.splice(f,0,e);
// document.write(color + "<br>");
// var h = prompt("Enter index number from where you want to start deleting elements of array");
// var g = prompt("Enter the numbers of elements you  want to delete");
// color.splice(h,g);
// document.write(color + "<br>");
